//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::upload_log::Entity as UploadLog;
pub use super::upload_statistics_cli_cfg::Entity as UploadStatisticsCliCfg;
pub use super::upload_user::Entity as UploadUser;
