//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upload_statistics_cli_cfg")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u32,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub cli_type: String,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub user: String,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub package: String,
    #[sea_orm(column_type = "Text")]
    pub configuration_info: String,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub ip: String,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub region: String,
    pub time: DateTime,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")", nullable)]
    pub bucket_hour: Option<String>,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")", nullable)]
    pub bucket_day: Option<String>,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")", nullable)]
    pub bucket_month: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
