//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upload_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub package: String,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub nav_url: String,
    #[sea_orm(column_type = "Text")]
    pub version: String,
    #[sea_orm(column_type = "Text")]
    pub logs: String,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub user: String,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub ip: String,
    pub time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
