//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upload_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub hash: String,
    #[sea_orm(column_type = "Text")]
    pub user_list: String,
    pub first_time: DateTime,
    pub last_time: DateTime,
    pub total_count: i32,
    pub status: i32,
    pub resolution_time: DateTime,
    #[sea_orm(column_type = "custom(\"TINYTEXT\")")]
    pub log_type: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
